name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: false
        default: 'Hello from the example workflow!'
  push:
  pull_request:

jobs:
  example-job:
    runs-on: ubuntu-latest
    name: An example job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run My Python Action
        uses: njannasch/action_playground_python@main
        with:
          python-version: '3.9'
          message: 'Hello from the example workflow!'

      - name: Write to workflow job summary
        run: |
          SUMMARY=$'# Job Summary\n## Second Level Heading\nHello World'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
